name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url: https://guptalab-erlangen.github.io/
          path-to-root: ./
          include-html: true

      - name: Commit sitemap
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap" || echo "No changes"
          git push
